# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shiju Samuel
tagline:          'My Revelations'
description:      'My Revelations'
url:              localhost:4000
baseurl:          /

author:
  name:           'Shiju Samuel'
  url:            https://twitter.com/helloshiju

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shijusamuel
